ordering:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: ordering
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tC1WSHgSeefCUjpEtEh
    access-key-secret: 2kZe6rQ7dIahqIuLdhSB7O4uVqtmUW
    bucket-name: ling-sky
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0