server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${ordering.datasource.driver-class-name}
      url: jdbc:mysql://${ordering.datasource.host}:${ordering.datasource.port}/${ordering.datasource.database}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ordering.datasource.username}
      password: ${ordering.datasource.password}
  redis:
    host: ${ordering.redis.host}
    port: ${ordering.redis.port}
    password: ${ordering.redis.password}
    database: ${ordering.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ordering.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      ordering:
        mapper: debug
        service: info
        controller: info

ordering:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcase
    # 设置jwt过期时间
    admin-ttl: 864000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    endpoint: ${ordering.alioss.endpoint}
    access-key-id: ${ordering.alioss.access-key-id}
    access-key-secret: ${ordering.alioss.access-key-secret}
    bucket-name: ${ordering.alioss.bucket-name}
